os: linux
dist: trusty
arch:
  - amd64
  - ppc64le
  - arm64
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
before_install:
- pip install codecov
- pip install requests
install:
- pip install -e .
script:
- coverage run -p tests/all_tests.py
- coverage run -p `which machinestate` -e -s -i 4 -o output.json
- coverage run -p `which machinestate` -c
- coverage run -p `which machinestate` -a
- coverage run -p `which machinestate` -j output.json
after_success:
- coverage combine
- codecov
cache: pip
