os: linux
dist:
- xenial
- trusty
- precise
- bionic
arch:
  - amd64
  - ppc64le
  - arm64
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
before_install:
- pip install codecov
- pip install requests
install:
- pip install -e .
script:
- coverage run -p tests/all_tests.py
- coverage run -p `which machinestate` -e -s
after_success:
- coverage combine
- codecov
cache: pip
