name: publish

on:
  push:
    tags:
      - v*
  workflow_run:
    workflows: [buildtest]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Set up Python
      - name: Pre-Install (generic)
        run: |
          python -m pip install requests
          python -m pip install setuptools
          python -m pip install --upgrade pip
      - name: Build package
        run: |
          python setup.py build sdist
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && startsWith(matrix.os, 'ubuntu')
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.pypi_password }}
